package main

// Candidate art for the cat design round of 2026-09-11. GENERATED from the
// drafting agents' returns -- each direction was drawn independently, rendered
// back to quadrant characters by its own author and looked at before being
// handed over, then validated mechanically here (the shipped cat is the
// positive control: see catAltsReport).
//
// Nothing in this file is wired into the product. It exists to be looked at.

var catAskAlts = []catAlt{
	{
		Key:  "pricked-ears",
		Name: "Pricked ears",
		Idea: "The skull band that today joins the two ears into one low ridge is deleted, so the ears stand free above open sky for a full character cell instead of half of one — the universal \"ears up, listening to you\" read, landing on the tallest, first-glanced part of the outline.",
		Note: "Only cell row 0 changes, and it changes completely. Today: ` ▐█▄▄▄▟█ ` — a continuous ridge across the crown with two bumps on it. New: ` █▙ ▟█ ` — two separate wedges with three cells of open sky between them and a flat skull a half-cell below. The ears do not get taller (row 0 is the ceiling); the HEAD gets a half-cell shorter under them, which is the only way to buy free-standing ear at this resolution, and it doubles the ear's visible standing height from one half-cell to two. With the face the app actually ships (faces.go:67, Ears: EarInnerDark, which paints cells 2 and 6 of row 0): today",
		Rows: []string{
			"..##..........##........",
			"..###........###........",
			"..####......####........",
			"..####......####........",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".###...#####...###......",
			".###...#####...###......",
			".#################......",
			".#######...#######......",
			".#################......",
			"..###############.......",
			"...#############........",
			"....###########.........",
			".....#########..........",
			"....###########.........",
			"...#############........",
			"..###############.......",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			"..###..#####..###.......",
			"..###..#####..###.......",
		},
		Risks: []string{
			"The whole difference lives in ONE of seven cell rows. It is the honest maximum at this resolution for an ears-only direction, not the loudest change available — from across the room the two poses still share six identical rows.",
			"The skull loses a half-cell of crown to buy the ear height, so the NeedsYou head reads slightly SMALLER than the Working head. That borrows a little of Worried's vocabulary (Worried is explicitly a shrink). Intended as 'ears up over a flat skull', but worth his eye.",
			"Constraint 2 as written says rows 8..11 at cols 4..5 / 12..13 must be open; the shipped CatBody does not satisfy that literally (holes are rows 8-9, ink at 10-11). I kept it byte-identical rather than introduce an eye change on an ears-and-head direction. If a full four-row socket is actually wanted",
			"face.go's ear mark lands differently now. EarInnerDark/EarInner paint cells 2 and 6, which are this pose's INNER ear cells — good. EarOuter paints cells 1 and 7, which are now the ear TIPS, so it would hollow the tip instead of the inner. Both styles want one look before shipping.",
		},
	},
	{
		Key:  "ears-clear-of-the-crown",
		Name: "Ears Clear of the Crown",
		Idea: "The cat's ears come up off its skull and stand free with a hole of sky between them — the skyline goes from one unbroken crown to two distinct pricked ears, and that is the whole edit.",
		Note: "Measured, not argued — I copied bitmap.go into a scratchpad package and rendered through the real ToQuadrant: Worried |▗▄▖ ▄▄ | Working | ▐█▄▄▄▟█ | ASK | █▙ ▟█ | <- this draft (mirrored, FaceLeft: | █▙ ▟█ | — exact mirror pair, survives the flip) Why THIS edit and no other, from the medium: 1. This sprite has exactly ONE edge that borders empty sky: the top. Every other place a shape change could live is compromised. The interior can only change by removing ink, and in a single flat coat a hole in the mass reads as damage, not anatomy. The bottom is the anchor and already spends its contrast o",
		Rows: []string{
			"....##........##........",
			"....###......###........",
			"....####....####........",
			"....####....####........",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".###...#####...###......",
			".###...#####...###......",
			".#################......",
			".#######...#######......",
			".#################......",
			"..###############.......",
			"...#############........",
			"....###########.........",
			".....#########..........",
			"....###########.........",
			"...#############........",
			"..###############.......",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			"..###..#####..###.......",
			"..###..#####..###.......",
		},
		Risks: []string{
			"The notch lives in one cell row out of seven. This does not replace the bright 'O' and the fast tail — it adds silhouette to them. Someone staring at the body will still be carried by the eye and the wag; the ask is now readable in a still screenshot, which it was not before.",
			"Breathing costs half the frames. At lift=2 the whole sprite drops two source rows and cell row 0 becomes ` ▄▖ ▗▄` over `▗▄██▄▄██▄` — the ear tips shrink to nubs and the sky gap slides down into cell row 1. It SURVIVES (I rendered it), but the loudest frame alternates with a quieter one roughly every",
			"The brief says the eye holes must stay open at rows 8..11, cols 4..5 and 12..13. The SHIPPED cat does not have them open there: row 10 is solid cols 1-17 and row 11 only breaks for the muzzle at cols 8-10. I left rows 8-11 byte-identical rather than cut holes that never existed, so his 2026-09-05 ru",
			"The ear pair's midpoint is now col 9.5 against the head's axis at col 9. Half a source pixel. Invisible at 12x7, and it is the price of the render being symmetric — perfect mirror symmetry in BOTH source and cell space is impossible on this sprite, because the body's axis (col 9) sits inside a cell ",
		},
	},
	{
		Key:  "paw-up-foot-off-the-sand",
		Name: "Paw up, foot off the sand",
		Idea: "A blunt paw stands clear of the cat's shoulder with a full column of sky behind it, and the foot that should be under it is missing from the sand.",
		Note: "I rendered it, not just drew it: halved and quadrant-packed by hand script, then re-run through the repo's own ParseBitmap/ToQuadrant (copied out to a scratch module) — the two agree cell for cell. Mirrored, lift 0, the ask is ``` █▙▄▄▄█▌ <- shipped, same frame: █▙▄▄▄█▌ ████████▌ ████████▌ ▖ █▙O██▙O█▌ ▖ █▙O██▙O█▌ ▌ ▀██████▀ ▌ ▀██████▛▘ ▜▖ ▗▟█████ █ <- paw, gap ▜▖ ▗▟█████▄ ▜▙███████ ▌ <- forearm, gap ▜▙████████▌ ▝▜█▀██▛▀▀▘ <- no foot ▝▜█▀██▛▜█▘ ``` Three signals, all of them silhouette, none of them shading: a solid cell of paw; a column of sky one cell wide and two cell rows tall between it an",
		Rows: []string{
			"...##.........##........",
			"...###.......###........",
			"...####.....####........",
			"...#############........",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".###...#####...###......",
			".###...#####...###......",
			".#################......",
			".#######...#######......",
			"..################......",
			"..###############.......",
			"....############........",
			"....###########.........",
			"##...#########..........",
			"##..###########.........",
			"##..############........",
			"##..#############.......",
			".#..#############.......",
			".#..##############......",
			".#..##############......",
			".#..##############......",
			".#################......",
			".#################......",
			".......#####..###.......",
			".......#####..###.......",
		},
		Risks: []string{
			"The limb rises from the body's bottom corner rather than standing above the shoulder, so it can read as \"paw held out to shake\" rather than \"paw raised to ask\". At 12x7 the shoulder is the ceiling: anything higher on this side touches the head, and the head cannot move because the eye glyphs are pin",
			"Once mirrored (the shipped composition) the paw is on SCREEN RIGHT, the frame-edge side, because the tail corridor owns screen left. The crab deliberately points its raised claw at the transcript; the cat cannot. A reader coming off the sand text sees the paw last.",
			"It spends two head pixels (row 12 col 1, row 14 col 3). The ask's jaw is one cell narrower at the bottom-left than the Working pose's, so on the state change the chin corner blinks off as the paw blinks on. I read that as motion, but it is a head change in a pose that was meant to change only the bo",
			"Under the breathing lift the gap above the paw narrows from a full cell to a half cell (a '▝' returns at cell 0, cell-row 3). The paw never fuses with the head, but its separation pulses — that is the one place the 2-row lift costs something.",
		},
	},
	{
		Key:  "chin-up-chest-lifted-sit",
		Name: "Chin up, chest lifted (sit-up)",
		Idea: "The head stays put and the whole body underneath it stands up: a neck appears where the shipped cat has none, the chest narrows into a straight lifted front, and the two forepaws plant apart with a clean cell of sand between them — the animal has gathered itself and is attending to you.",
		Note: "I rendered it rather than reasoning about it: a throwaway Python port of ToQuadrant plus cat.go's tail() curve, the breathing lift, and the Base face overlays (nose at cell 4 row 3, eyes at cells 2/6 row 2, toes at cells 2/6 row 6), at /private/tmp/claude-501/-Users-lucasgarzoli-Documents-claude/7d7c12ec-b8c0-4e31-9ef6-f3f9b0a0950c/scratchpad/catask-situp/. What lands, exhaled (lift 0): ship ask | ▐█▄▄▄▟█ | | ▐█▄▄▄▟█ | |▐████████| |▐████████| |▐█o▟██o▟█| |▐█O▟██O▟█| |▝▜██▾███▀| |▝▜██▾███▀| | ▄█████▙▖| | ▄███▄ | |▐████████| | ███████▄| |▝█▖▜██▗█▛| | █▖█ █▗█▀| Three things survive at 12x7 in one",
		Rows: []string{
			"...##.........##........",
			"...###.......###........",
			"...####.....####........",
			"...#############........",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".###...#####...###......",
			".###...#####...###......",
			".#################......",
			".#######...#######......",
			".#################......",
			"..###############.......",
			"...#############........",
			"....###########.........",
			"......######............",
			"......######............",
			"....##########..........",
			"....##########..........",
			"..##############........",
			"..##############........",
			"..################......",
			"..################......",
			"..######..########......",
			"..######..########......",
			"..######..######........",
			"..######..######........",
		},
		Risks: []string{
			"Bobblehead. A 9-cell head on a 5-cell neck can read as a head balanced on a post rather than a cat sitting tall. I tuned this: the pure 3-cell neck (rows 16-21 all at cols 6-11) tipped over into mushroom and I stepped it out 3 -> 5 -> 7 cells instead. It is still the closest failure mode, and it is ",
			"The delta thins out while the cat breathes in. On the lift=2 half of the cycle the neck softens from a hard notch to a taper and the base closes up to a solid bar — 9 differing cells instead of 13. The ask is still legible (the neck notch is the part that survives), but the pose is strongest on the ",
			"The body now sits half a cell in from the head on the LEFT (col 2) while staying flush on the right (col 17, where the tail roots). That is a deliberate half-cell of asymmetry to keep the tail attached, and it very slightly weights the animal toward its tail side. Invisible to me at 12x7; flagging i",
			"The whole-cell gap between the feet is open at the bottom edge, so it should read as ground between two paws — but at a glance on dark sand it could read as a bite taken out of the sprite. If that happens, rows 24-25 can go back to solid (cols 2-17) and the split confined to rows 26-27; that costs t",
		},
	},
	{
		Key:  "cocked-head-one-ear-down",
		Name: "Cocked head — one ear down, head carried over",
		Idea: "One ear reaches the top row and the other stops half a cell short behind a notch, the skull's mass is carried a cell toward the raised ear while the jaw swings the other way, and the eye line slants — a cat holding its head over to ask you something.",
		Note: "Rendered through the repo's own ToQuadrant, unmirrored at lift=0 / lift=2, and mirrored (the shipped orientation): ``` ▗██▄▄▄ ▄▄ ▄▄ ▄▄ ▄▄▄██▖ ▗█▀███████ ▟█████▄██ ███████▀█▖ ▟█O███O██▘▄ ▐█O███O██▛ ▝██O███O█▙ ▜███v█▀▘ █ ██▄█v█▄▛▀ █ ▙▖ ▝▀█v███▛ ▄█████▙▖ █ ▝▀████▄▖ █ ▜▄▗▟█████▄ ▐████████ █ ▗███████▙ █ ▐████████▌ ▝█▛▜██▀█▛▝▘ ▐████████▗▛ ▜█▀██▛▜█▘ ``` against the shipped body, which Working and NeedsYou both draw today: ``` ▐█▄▄▄▟█ ▗▄ ▗▄ █▙▄▄▄█▌ ``` 1. THE EAR ROW IS THE WHOLE THING, and it is one flat colour against sky. Shipped: two full-height blocks. Here: one full-height block (`██`, cells 2-3",
		Rows: []string{
			"......##................",
			"....####................",
			"...###########..####....",
			"...###########..####....",
			"..##################....",
			"..##################....",
			".###..##############....",
			".###..#############.....",
			".###..######..#####.....",
			".###..######..#####.....",
			"####..######..####......",
			"####..######..####......",
			"###############.........",
			"##############..........",
			".###########............",
			"..##########............",
			".....#########..........",
			"....###########.........",
			"...#############........",
			"..###############.......",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			"..###..#####..###.......",
			"..###..#####..###.......",
		},
		Risks: []string{
			"THE BREATH EATS HALF THE SIGNAL, and this is the honest answer to 'does it survive the halving'. lift=2 empties the top quadrant row for ANY sprite, so at lift=2 cell row 0 collapses to ` ▄▄` — one mark where the shipped cat shows two (`▗▄ ▗▄`). The pose still reads one-eared, and the notch survives",
			"THE EYE-LINE SLANT IS NEUTRAL AT lift=2, NOT INVERTED — and it took a measurement to get there. Both eye holes are 4-6 rows deep, so at lift=2 both push into cell row 3 and both eyes get a `▄` beneath: the slant simply vanishes for that phase. My first draft put the ear notch at cols 12-13, which is",
			"THE OFF-CENTRE MUZZLE IS NOT IN THE BITMAP, and I could not put it there. Measured four placements: a notch at cols 6-7 or cols 10-11 on rows 10-11 each sits against an eye hole and merges into one 4-px sky run that reads as a smeared eye (rendered both, they are worse than nothing); cell 4 is the o",
			"The asymmetry is deliberate and it is also the risk: at a glance the low ear can read as the head simply being taller on one side rather than as a second ear, because it sits at the head's outer shoulder rather than clear of it. The single empty cell of notch is the only thing separating them, and a",
		},
	},
}

var catDoneAlts = []catAlt{
	{
		Key:    "crab-settled-on-the-sand",
		Animal: "crab",
		Name:   "Settled on the sand",
		Idea:   "The crab has sat down — it is the only pose with no daylight under it: the body is spread flat on the sand, the legs are folded away, and the claws are down beside the head instead of held up over it.",
		Note:   "All four other poses share crabLower verbatim, so their bottom three cell rows are byte-identical: `▗█▀██████▀█▖ / █▘ ▝████▘ ▝█ / ▐ ▝▀▀▘ ▌` — a shell standing on splayed legs with two open wedges of sand beneath it and four thin points of contact. This Done is the only pose whose underside is closed: `████████████ / █▄████████▄█ / ▀██ ████ ██▀`. That alone separates it from every one of them in a still, at the largest region of the sprite, with no motion needed. Per pose: vs WORKING — Working has both claws up at cell row 0 (`█▄█ █▄█` on the top row) above a standing body; this has an EMPTY to",
		Rows: []string{
			"........................",
			"........................",
			"........................",
			"........................",
			"##..##............##..##",
			"##..##............##..##",
			"######............######",
			"######............######",
			"..####..##....##..####..",
			"..####..##....##..####..",
			"..##......####......##..",
			"..##......####......##..",
			"..####################..",
			"..####################..",
			"########################",
			"########################",
			"########################",
			"########################",
			"########################",
			"########################",
			"##..################..##",
			"##..################..##",
			"########################",
			"########################",
			"######..########..######",
			"######..########..######",
			"..####..########..####..",
			"..####..########..####..",
		},
		Risks: []string{
			"It needs a SECOND bitmap and a second wiring point. drawCrab must pick a Done-specific lower (`lower = crabDoneLower` when st == Done, beside the existing crabLowerStep branch), and crab_near.go must do the same: nearPoseFor at rung 2 (crab_near.go ~line 660) composes crabUpper(st,t) over crabLower,",
			"The breath undoes the premise for half of every cycle. Done is not in crabBreathPeriod's switch, so it gets the default 3.6 s and the standard 2-source-row lift — which raises the whole body half a cell and lifts the new flat foot off the sand. It stays distinct (row 6 reads ` ▀▀ ▀▀▀▀ ▀▀ ` against e",
			"Cell row 4 renders as twelve fully-inked cells — the first completely solid cell row any crab pose has had. On sand, inside plotRim's cleared ring, that is a solid salmon bar and it may read as a block rather than a body. I tried the obvious fix (a shoulder notch that makes the flank `▀██████████▀`)",
			"It can read as 'flattened' or 'squashed' rather than 'content'. The only things carrying contentment are the '^' eye glyph and the claws still held up beside the head; there is no smile channel at this size. If someone reads it as the crab being crushed, the claws need to go up half a cell, which co",
		},
	},
	{
		Key:    "cat-the-loaf",
		Animal: "cat",
		Name:   "The Loaf",
		Idea:   "The cat has folded its legs away and settled into one low block with nothing showing underneath it, so a still frame shows an animal that has put itself down rather than one that is holding itself up to work.",
		Note:   "Rendered back through the real path (lift, tail curve, halve, 2x2 quadrant pack, eye glyph plotted) and read beside the shipped poses at both breath phases. Working, Resting and NeedsYou all draw the same CatBody, so one number covers all three: 13 of 84 cells differ at a matched breath phase and 10 at the other, against 0 today — and every differing cell is on the OUTLINE, not the interior. Cell row 4 goes from the waist pinch ' ▄█████▙▖' to '▐████████', and the foot row goes from '▝█▛▜██▀█▛' — three blocks with daylight between them — to one unbroken base '▐███▄████'. The still reads \"has a ",
		Rows: []string{
			"...##.........##........",
			"...###.......###........",
			"...####.....####........",
			"...#############........",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".###...#####...###......",
			".###...#####...###......",
			".#################......",
			".#######...#######......",
			"...#############........",
			"....###########.........",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#######..########......",
			".#######..########......",
			".#################......",
			".#################......",
		},
		Risks: []string{
			"It can be read as \"asleep\" rather than \"finished\" by someone seeing it cold. The defence is inside the pose: the head is at full height and the ears are unchanged, which no sleeping cat does — a cat asleep curls or lies over, head down. And it cannot collide with Resting, which is the shipped seated",
			"The lower half is now 27 solid cells with one notch. At one flat colour that mass could read as a rock rather than an animal if the coat and the sand sit close in tone at some hour. That is a question for the real beach at the worst hour, not for this grid — look before shipping.",
			"The weak breath phase is lift 2, 10 cells rather than 13, because the shipped cat's own foot gaps are clipped out of the box there too and only the waist and the paw notch carry the difference. Pinning lift = 0 for Done would make every screenshot the strong frame and stillness is itself on-message,",
			"The tail now contradicts the pose. Done holds it full length, raised, at wag 0 — the brief already found that cue dies in a still, and on a loafed body a raised tail is the wrong animal. The bitmap keeps cols 18-23 clear below row 10 so anything can still be drawn there, but the tail needs its own r",
		},
	},
	{
		Key:    "crab-claws-down-open",
		Animal: "crab",
		Name:   "Claws Down, Open",
		Idea:   "Both claws have come down onto the shoulders and fallen open — the top jaw lying flat, the hinge standing at the inner end, the shell's own shoulder as the lower jaw — so the crab is visibly holding nothing up, and because an open pincer is a POSITION and not a motion, a screenshot still shows it.",
		Note:   "Rendered through the shipped path (ParseBitmap -> breath lift -> Mirrored -> ToQuadrant -> eye plot at {4,7} row 2), the top three cell rows are, at breath lift 0: Done NEW ▄▄▄ ▄▄▄ / █ █ / ▜██▄^▄▄^▄██▛ Working █▄█ █▄█ / ▀█▀ ▀█▀ / ▗█▄▄o▄▄o▄▄█▖ Resting ▄ ▄ ▄ ▄ / ███ ███ / ▗█▄▄-▄▄-▄▄█▖ NeedsYou █▄█ / ▀█▀ █▄█ / ▗█▄▄O▄▄O▄▄█▖ Worried (empty) / ▄▄ █ █ ▄▄ / ▜██▄o▄▄o███▖ vs WORKING (14 cells of 84 differ at lift 0, 10 at lift 2): Working's claw is a solid tower, full cells in row 0 and row 1 on the outer three columns; Done's row 1 is nearly EMPTY — one hinge cell a side — and row 0 is a half-height ba",
		Rows: []string{
			"........................",
			"........................",
			".#####............#####.",
			"######............######",
			"....##............##....",
			"....##............##....",
			"....##............##....",
			"....##............##....",
			"######..##....##..######",
			".#####..##....##..#####.",
			"..####################..",
			".######################.",
			"########################",
			"########################",
			".######################.",
			"..####################..",
			"...##################...",
			"..##..############..##..",
			"..##..############..##..",
			".##....##########....##.",
			".##....##########....##.",
			"##......########......##",
			"##......########......##",
			"##.......######.......##",
			".#.......######.......#.",
			".#........####........#.",
			".#....................#.",
			".#....................#.",
		},
		Risks: []string{
			"The near pose at rung 1 has no Done at all. crab_near.go:nearPoseFor only branches on NeedsYou (nearLevel1 / nearAsk1), so at rung 1 Done draws the Working body and only the eye art changes — the same defect this fixes, one rung up. Rung 2 doubles crabUpper, so it inherits this art for free (rendere",
			"The nearest neighbour is Resting at 10 cells, and the shared half of that is the row-0 bar. If anyone later raises Resting's claws or closes this pose's mouth, re-measure — 10 is the margin, not a cushion.",
			"Done's row 2 (▜██▄) is identical to Worried's left shoulder in the mirrored frame, because crabWorried's arms are authored ASYMMETRIC (cols 2-7 / 18-23) and the mirror lands its left arm on cols 0-5 where this pose's shoulder is. All 14 cells of Done-vs-Worried separation are carried by rows 0 and 1",
			"TestEveryCrabStateLooksDifferent cannot catch what this fixes. It keys on the whole canvas INCLUDING the eye glyph, so shipped Done passed it with zero body cells different from Working. If this pose is landed, the guard worth adding is a BODY-ONLY comparison at matched breath phase with the eye gly",
		},
	},
	{
		Key:    "cat-chin-up",
		Animal: "cat",
		Name:   "Chin Up",
		Idea:   "The top of the animal has gone wide and square — the ears have fallen open to the outer corners of the head instead of standing inboard, and a neck has appeared under the chin with the chest filled out below it, so the cat is sitting up rather than hunched over its work.",
		Note:   "Measured on the real renderer (ParseBitmap → breath shift → TailAt → ToQuadrant), not asserted. **11 cells differ from Working, at BOTH breath phases, with the SAME eye glyph on both sides and both tails pinned at wag 0** — so neither the eye nor the tail contributes a single cell of it. That is the whole point: today the number is 0. Resting and NeedsYou share CatBody, so it is 11 against each of them too. Worried is 15. I swept every frame the other four states can be caught in — 2001 tail phases × 2 breath phases × 4 states = 16,008 frames — and asked for the FLOOR, not the mean: **0 frames",
		Rows: []string{
			"##..............##......",
			"####..........####......",
			"..####......####........",
			"...#############........",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".###...#####...###......",
			".###...#####...###......",
			".#################......",
			".#######...#######......",
			".#################......",
			"..###############.......",
			"....###########.........",
			".....#########..........",
			"...#############........",
			"..###############.......",
			".#################......",
			".#################......",
			"..###############.......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			".#################......",
			"..###..#####..###.......",
			"..###..#####..###.......",
		},
		Risks: []string{
			"THE CHEST DOES ZERO WORK AGAINST WORRIED. Cell row 4 renders `▗███████▙` — which is EXACTLY what CatWorried's hunched shoulders already render. Measured, not guessed: Worried's rows 14-19 are 13,11,13,15,15,17 and produce the identical cell. So the whole Done/Worried separation rides on cell rows 0 ",
			"THE EARS BREAK THE CAT'S OWN PIXEL SYMMETRY, DELIBERATELY. The shipped body is symmetric about column 9 (x↔18-x), which can NEVER render cell-symmetric — cell cx maps across cells 8-cx and 9-cx. Rows 0-2 are instead symmetric about 8.5 (x↔17-x), which is what makes the rendered top row an exact pali",
			"A 1PX INDENT AT SOURCE ROW 20. The chest reaches 17 wide at rows 18-19 and base row 20 is 15, so the raw art dips one pixel per side for one row. Measured: INVISIBLE in ToQuadrant at both breath phases (row 20 is OR'd with row 21), VISIBLE in ToBraille and ToChars. Only the quadrant path ships for t",
			"NOT COMPARED AGAINST THE ASK POSE. That draft is in flight in parallel and the brief says it also lives in the top of the silhouette. This pose's axis is WIDTH at the top (ears out to the corners, crown squared). If the ask also widens the top rather than raising or tilting it, the two collide and o",
		},
	},
}

var catRungAlts = []catRung{
	{
		Key:  "lean-in-sit",
		Name: "Lean-in sit",
		Idea: "The cat has taken a step and dropped its weight onto its forehand: head broad and low with wide-set ears, almost no neck, a short foreshortened body, and front paws braced wider than the head — so rung 1 reads as an animal that moved, not a picture that grew.",
		Note: "RENDERED, NOT REASONED. Both blocks were packed through a copy of ToQuadrant (halve rows, pack 2x2) from the exact strings above, with the tail and the eye glyphs drawn on, and looked at. LEVEL and ASK at rest: ▟█▙▖ ▗▟█▙ ▟█▙▖ ▗▟█▙ ▐████▙▟████▌ ▐████▙▟████▌ ▐██████████▌ ▐██████████▌ ▐█o▐████▌o█▌ ▐█O▐████▌O█▌ ▝████▀▀████▘ ▝███▛▀▀▜███▘ ▀██████▀ ███▄▄███ ▟████████▙ ▟████████▙ ▄██ ▐██▌ ██▄ ▄██ ▐██▌ ██▄ ███ ▐██▌ ███ ███ ▐██▌ ███ THE POSTURE, and why each piece is not a scale factor. I also generated the naive 24x28 -> 32x36 nearest-neighbour scale as a control and rendered it; it comes out as ` █▙▄ ",
		Upper: []string{
			".####..............####.........",
			".####..............####.........",
			"#######..........#######........",
			"#######..........#######........",
			".##########..##########.........",
			".##########..##########.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".###...##########...###.........",
			".###...##########...###.........",
			".###...##########...###.........",
			".###...##########...###.........",
			".######################.........",
			".######################.........",
			"..########....########..........",
			"..########....########..........",
			"....################............",
			"....################............",
			"......############..............",
			"......############..............",
		},
		UpperAsk: []string{
			"...####..........####...........",
			"...####..........####...........",
			"..#######......#######..........",
			"..#######......#######..........",
			".##########..##########.........",
			".##########..##########.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".###...##########...###.........",
			".###...##########...###.........",
			".###...##########...###.........",
			".###...##########...###.........",
			".######################.........",
			".######################.........",
			"..#######......#######..........",
			"..#######......#######..........",
			"....######....######............",
			"....######....######............",
			"....################............",
			"....################............",
		},
		Lower: []string{
			"...##################...........",
			"...##################...........",
			"..####################..........",
			"..####################..........",
			"..####...######...####..........",
			"..####...######...####..........",
			"######...######...######........",
			"######...######...######........",
			"######...######...######........",
			"######...######...######........",
			"######...######...######........",
			"######...######...######........",
		},
		EyeCells: [2]int{2, 9},
		EyeRow:   3,
		Risks: []string{
			"THE BREATH DIRECTION IS NOT MINE TO SET AND IT CHANGES THE EARS. drawCrabNear lifts with src.at(sx, sy+lift), which moves the art UP; the cat's own Draw uses sy-lift and moves it DOWN. Rendered both: DOWN is right for this art (the ear tips shorten to ▗▄▖ and the paws stay planted on the sand, which",
			"THE HEAD IS 11 CELLS AND THE CHEST IS 10 — a 10% inequality. It reads to me beside the control render, but it is the subtlest of the five posture cues and it is the one carrying the actual word 'foreshortening'. If he looks at this live and says it still reads as a zoom, the cheap next move is to na",
			"HEAD-AND-EARS ARE 5 OF 9 CELL ROWS (55%) against rung 0's 57% and rung 2's 50%. I deliberately did NOT push the head bigger or drop the eyes lower in the face, though both would have shouted 'tipped toward you' — drafted and rendered an eyes-at-cell-row-4 version and it read as a kitten, and worse, ",
			"THE ASK MOVES THE EARS ONE CELL. That is the same order as the crab's raised claw only when you count it with the mouth and the throat; on its own it is small. If the ask has to read from across the room, the mouth hole is the part to grow, not the ears.",
		},
	},
	{
		Key:  "the-faithful-scale-up",
		Name: "The Faithful Scale-Up",
		Idea: "The shipped cat at 1.29x, with the extra pixels spent only on the three features the 12x7 had to abbreviate away: the ear point, the muzzle, and the paw split.",
		Note: "CORRECTION — upper[0] in the JSON above got a stray '!' at index 4 during serialisation. The correct row 0 is identical to row 1: \".....##..........##.............\" (ink at cols 5,6 and 17,18). Everything else is exactly as rendered. WHAT IT LOOKS LIKE (rendered through a copy of ToQuadrant, level then ask, 16x9, eye glyph drawn in): ▟▙▄▄▄▄▟▙ ▟▙▄ ▄▟▙ ▗██████████▖ ▗██████████▖ ▐██████████▌ ▐██████████▌ ▐█▐▌████▐▌█▌ ▐█()████()█▌ ▝▜███▄▄███▛▘ ▝▜███ ███▛▘ ▟██████▙ ▟██████▙ ▗██████████▖ ▗██████████▖ ▐██████████▌ ▐██████████▌ ▝██▀▜██▛▀██▘ ▝██▀▜██▛▀██▘ THE SCALE. The shipped body is 17 source columns",
		Upper: []string{
			"....!##..........##.............",
			".....##..........##.............",
			"....#####......#####............",
			"....################............",
			"...##################...........",
			"..####################..........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".###....########....###.........",
			".###....########....###.........",
			".###....########....###.........",
			".###....########....###.........",
			".#########....#########.........",
			".#########....#########.........",
			"...##################...........",
			"....################............",
			".....##############.............",
			"......############..............",
			".....##############.............",
			"....################............",
		},
		UpperAsk: []string{
			".....##..........##.............",
			".....##..........##.............",
			"....#####......#####............",
			"....######....######............",
			"...##################...........",
			"..####################..........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".###....########....###.........",
			".###....########....###.........",
			".###....########....###.........",
			".###....########....###.........",
			".#########....#########.........",
			".#########....#########.........",
			"...#######....#######...........",
			"....######....######............",
			".....##############.............",
			"......############..............",
			".....##############.............",
			"....################............",
		},
		Lower: []string{
			"..####################..........",
			"..####################..........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			"..####...######...####..........",
			"..####...######...####..........",
			"..####...######...####..........",
		},
		EyeCells: [2]int{2, 8},
		EyeRow:   3,
		Risks: []string{
			"upper[0] in my JSON carries a stray '!' at index 4 from serialisation. The correct row is \".....##..........##.............\" — identical to upper[1] and to upperAsk[0]. ParseBitmap would read '!' as empty and silently drop one pixel of the left ear tip, turning ▟▙ into ▗▙ on the left ear only and br",
			"THE BREATH RE-PHASES THE GRID. A 2-source-row lift is half a cell, so it does not move the art, it re-packs it. Rendered both ways: on the lifted half of every breath the ear peaks collapse from ▟▙ to ▗▖ and the paw split closes completely (the bottom cell row goes solid). This is NOT new — I render",
			"THE MUZZLE IS THE ONE THING A READER CAN NAME. It is invisible at 1x (OR'd away) and visible here, so a side-by-side reader could say \"it has a mouth now\". I judged that inside the brief — it is a feature the 12x7 had to abbreviate, not an invention — but it is the single place the \"cannot name what",
			"THE ASK MAY BE TOO QUIET. Both its changes are centred and modest: a saddle that drops and a notch that doubles. Against the crab's raised claw this is a whisper. It leans on the alert eye glyph carrying its share. Put the two poses side by side on the beach before ruling — if it does not read, the ",
		},
	},
	{
		Key:  "whisker-rung",
		Name: "Whisker Rung",
		Idea: "A seated front-view cat at 32x36 that spends the extra pixels on the face he named — two whisker pairs that stick out past the cheek, a heart-shaped nose hole, a tabby brow, and toed paws — and asks by pricking its ears and raising one forepaw beside its chin.",
		Note: "RENDERED, NOT REASONED. Every claim below was read off a render. I copied ParseBitmap and ToQuadrant out of internal/companion/bitmap.go into a standalone Go program and ran my art through the real transform; a Python port agrees with it character for character, and the Python is what I iterated in. I also rendered the shipped 24x28 CatBody through the same tool to get a baseline, and rendered every pose at lift 0 and lift 2. GEOMETRY. 32x36 -> 16 x 9 cells. The body is drawn in columns 0..23 (cells 0..11) and is mirror-symmetric about x=11.5, so col c maps to col 23-c: that maps cell j to cel",
		Upper: []string{
			"................................",
			"................................",
			".....####......####.............",
			".....####......####.............",
			"....######....######............",
			"....######....######............",
			"...########..########...........",
			"..####################..........",
			".########..##..########.........",
			".########..##..########.........",
			".######################.........",
			".######################.........",
			".####....######....####.........",
			".####....######....####.........",
			"...##################...........",
			"...##################...........",
			"##########....##########........",
			"##########....##########........",
			".....######..######.............",
			".....######..######.............",
			".####.############.####.........",
			".####.############.####.........",
			"......############..............",
			"......############..............",
			"...##################...........",
			"..####################..........",
			".######################.........",
			".######################.........",
		},
		UpperAsk: []string{
			".....####......####.............",
			".....####......####.............",
			"....######....######............",
			"....######....######............",
			"...########..########...........",
			"...########..########...........",
			"...########..########...........",
			"..####################..........",
			".########..##..########.........",
			".########..##..########.........",
			".######################.........",
			".######################.........",
			".####....######....####.........",
			".####....######....####.........",
			"...##################...........",
			"...##################...........",
			"##########....##########........",
			"##########....##########........",
			".....######..######.............",
			".....######..######.............",
			"####..############.####.........",
			"####..############.####.........",
			"####..############..............",
			"####..############..............",
			".####################...........",
			".#####################..........",
			".######################.........",
			".######################.........",
		},
		Lower: []string{
			".######################.........",
			".######################.........",
			".######################.........",
			".######################.........",
			".#####..########..#####.........",
			".#####..########..#####.........",
			".##.##..##.##.##..##.##.........",
			".##.##..##.##.##..##.##.........",
		},
		EyeCells: [2]int{3, 8},
		EyeRow:   3,
		Risks: []string{
			"The ask/level EAR channel is partly washed out by the breath. The level cat's exhale ears and the ask cat's inhale ears render the same glyphs (\"▗▄▖\"). They still differ at cell row 1 and at the paw row, and the O-versus-o glyph is the shipped ask signal anyway, but the ears alone are not decisive i",
			"The RAISED PAW weakens on the inhale: \"██ \" becomes \"▄▄▝\" — a shoulder bulge with a narrower gap rather than a crisp block. Rendered; still distinguishable from the level pose's \"▗▄▞\", but not as clean.",
			"The TABBY BROW is the weakest detail on the sheet — two one-cell sky notches on the forehead. Against the sea it may read as damage rather than markings. It is one edit to delete (put rows 8-9 back to a plain 1..22 span) and nothing else depends on it.",
			"The NOSE is a hole, so it shows sky through the face the way the eyes do, and at two cells wide it is a bigger hole than the shipped muzzle gap (which never renders at all — face.go says so, and I confirmed it). If it reads as a puncture, narrowing rows 16-17 from columns 10..13 to 11..12 turns it i",
		},
	},
}
